# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  utils-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: false 
          node-version: latest 

workflows:
    execute-task:
      jobs:
        - node/run:
            npm-run: lint 
        - node/test
        - node/run:
            npm-run: build 